server:
  port: 7001
  tomcat:
    threads:
      max: 400
spring:
  application:
    name: seckill-web
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    #lettuce:
    #  pool:
    #    enabled: true
    #    max-active: 100
    #    max-idle: 20
    #    min-idle: 5
    password: 1234
rocketmq:
  name-server: 172.18.23.195:9876
  producer:
    group: product-group
    send-message-timeout: 3000 # ?????????
    retry-times-when-send-async-failed: 3  # ???????????????
    max-message-size: 4194304  # ?????????