rocketmq:
  name-server: 172.18.23.195:9876
  producer:
    group: springboot-producer-group
    send-message-timeout: 3000  # ?????????
    retry-times-when-send-async-failed: 2  # ????????????
    max-message-size: 4194304  # ???????