server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/seckill
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 1234
rocketmq:
  name-server: 172.18.23.195:9876
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ??????